# Generated by Django 3.2.5 on 2021-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesgcont', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
