# Generated by Django 3.2.5 on 2021-07-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210721_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('number', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('last_product_id', models.IntegerField(blank=True, null=True)),
                ('product_searched', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('short_desc', models.CharField(max_length=1000)),
                ('page', models.URLField()),
            ],
        ),
    ]
