# Generated by Django 3.2.5 on 2021-08-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.URLField(default='https://www.buildquickbots.com/whatsapp/media/sample/jpg/sample01.jpg'),
        ),
    ]
